title: "TheWizardBay"
description: "Keep the wizards at bay"
baseurl: ""
url: "https://blog.thewizardbay.cc"

markdown: kramdown
theme: null
permalink: /posts/:title/

collections:
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:title/
