title: "TheWizardBay"
description: "Keep the wizards at bay"
baseurl: ""          # empty for root, /repo-name for project page
url: "https://blog.thewizardbay.cc"  # the base hostname & protocol for your site

markdown: kramdown
theme: null           # custom CSS
permalink: /posts/:title/   # shortest possible permalink
