#+TITLE: Ilghar Kus 的 Blog
#+OPTIONS: num:0

* Before reading
这里是我的一些想法以及心情的汇总，如果想看技术类文章请返回到主页并在 =Articles= 栏中点选。

* Blogs
** 2021/02/01
还是心累，这段时间也没时间打理博客或者写东西。

学校的屁事太多太忙。忙里偷闲过了一个学期然后期末绩点成功爆炸。

然后寒假还住了次院，然后现在心态平和至极。

本来自己也不是什么喜欢社交的人，结果偌大的邯郸校区硬是没有找到几个合适的人去组织一个squad。

人都快抑郁了。
** 2020/10/17
心累，已经好几天没有接受或产出有质量的东西了。

尝试看了几页Perl，但是还是以失去兴趣为结果，尝试去学一些Sec相关的东西，结果发现整个行业发展了太多以至于我完全跟不上了。

然后我通宵了一晚上结果还是没有做出来什么有意思的东西，折腾一个多系统的Bootable USB折腾了几个小时还是无果而终。

想买好多东西但是没钱。

想学好多东西但是学不下去，要么就是没时间学。

或许是我太急于求成了。沉淀和积累是很重要的。折腾也是很重要的。

** 2020/10/13 
今天把昨天写到的函数写掉了，写起来还觉得挺简单。
然后这里是代码，写的很lowb


#+BEGIN_SRC emacs-lisp
  (defun blog-add-article-to-index (article-name)
  "自动在我的博客主页目录里更新新写的文章。"
	(if (file-exists-p "../index.org") ;; 判断文件是否存在，防止乱用。
	    ()
	  (write-line "Index.org doesn't exist!"))
	(interactive
	 (list (file-name-nondirectory(buffer-file-name)))) ;; 获取当前buffer的文件名
	(progn
	  (find-file "../index.org")  
	  (goto-line 7)  ;; 到达“article”那一行然后新建行
	  (open-line 1)
	  (insert "** [[" "./article/" article-name "][" (replace-in-string article-name ".org" "") "]]")
	;; 插入链接
	  (save-buffer) ;; 保存
  ))
#+END_SRC

** 2020/10/12 
今天是开通Blog功能的第一天。

本来我把我写的那些文章叫做Blog，后来想想有些不对劲，应该叫做Articles，Blog应该是用来记录自己的一些想法和心情用的。

于是就换了。

然后我就开始在这个页面上写Blog。

感觉还不错，至少不用写什么智障的朋友圈和QQ空间了。

连基本的富文本格式都不支持。

好的，我现在有点闲时间了，准备仔细讲一下我的这个个人站点是如何运行的。

首先，你们看到的所有HTML页面都是我在本地写完OrgFile之后用 =ox-twbs= 这个插件Export成HTML文档。

这个插件应该是Hackable的，但是具体的方式我还没有来得及开整，最近读书读疯了，学校的作业都快没时间做。

比如我用org-mode写完了一篇文章，然后将它导出为了HTML格式储存在OrgFile所在文件夹内，（一般的博客文章都是在 =./articles= ）

然后我就打开index.org在 =articles= 一栏加入我新写的那篇文章的orgfile的链接（默认快捷键是 =C-c C-l= ）

（其实严格意义上来说是要插入html链接，但是我实验过ox-twbs会自动将指向orgfile的文件替换成指向对应的HTML文件链接）

然后导出HTML，然后执行一个自己写的函数，自动完成 = git commit && git push = 一系列流程。

我觉得我有能力把在index.org里插入链接的事写个elisp函数自动化，但是因为太忙而且太懒一直没兴趣和动力去做。

整个流程大概就是以上。
