#+TITLE: Copyleft (README)
#+AUTHOR: Ilgharkus

* Before you attempt to do anything
- All of the content on this site is produced by yours truly, except the part that were indicated as quoted, paraphrased or
  #+BEGIN_QUOTE
    have used this kind of format
  #+END_QUOTE
  to declare the part is quoted.
- This site does not track you or run any non-free JavaScript code.

* Licensing
- Any content produced by yours truly is licensed under [[https://www.gnu.org/licenses/fdl-1.3.html][GNU Free Document License]], except those with explicit labelling or annotation.
  #+BEGIN_QUOTE
  The purpose of this License is to make a manual, textbook, or other functional and useful document "free" in the sense of freedom: to assure everyone the effective freedom to copy and redistribute it, with or without modifying it, either commercially or noncommercially. Secondarily, this License preserves for the author and publisher a way to get credit for their work, while not being considered responsible for modifications made by others.
  #+END_QUOTE

- All of my contents are available in their original =.org= format and available on the [[https://gitlab.com/ilghar_kus/blog][Site Repo]].


* Stack
- This site uses  [[https://docs.gitlab.com/ee/user/project/pages/index.html][GitLab Pages]].
- This site is generated using  [[https://orgmode.org/][Org Mode]], licensed under [[https://www.gnu.org/licenses/gpl-3.0.html][GNU Public Licence ver.3.0+]].
