#+title: Elements of Set Theory : The Note
#+AUTHOR: Ilghar Kus
#+OPTIONS: toc:nil
#+DATE: <2021-04-03 Sat>
This is my note during the reading
of the book /Elements of Set Theory/ by /Herbert B. Enderton/ .

The book is great.

#+TOC: headlines 2

* Chapter 1 /INTRODUCTION/
** Baby Set Theory
   In a naive approach, here is some definition.
   - A /set/ is a collection of things(called its /members/ or /elements/),
     and the collection being regarded as a singel object.
   - $t\in A$ means $t$ is a member of $A$, and $t\notin A$ means $t$ is not a member of $A$.
   - $A==B$ could be translated that $A$ has the exact same members as $B$, in which case,
     $A$ could be $\{2,3,5,7\}$ and $B$ could be the set of all solutions to the equation
     $x^4-17x^3+101x^2-247x+210=0$

     to which, we say:

   *Principle of Extensionality* $\quad$ If two sets have exactly the same members,
   then they are equal.

   In a less naive approach, we could say:

   *Principle of Extensionality* $\quad$ If $A$ and $B$ are sets s.t. for $\forall t$
   \[
   t\in A \iff t\in B
   \]
   then $A=B$.

   - Empty set, noted as $\emptyset$, has no members at all.
     and it's the only set with no members.

   - $\emptyset \in \{\emptyset\}$ and $\emptyset \notin \emptyset$, so $\emptyset \neq \{\emptyset\}$

   - *Union and Intersection* $\quad$ noted respectively as $\cup$ and $\cap$,
     means all elements of $A$ and/or $B$ and all elements of $A$ and $B$

   - The set of all subsets of $A$ is noted as /power set/ $\mathscr{P} A$ of $A$,
     also could be noted as $2^{A}$

   - /Method of abstraction/ $\quad$ is a very flexible way of naming a set.
     Notation used for the set of all objects $x$ s.t. the condition P(x) holds is
     \[
     \{x|P(x)\}
     \]

   This method causes two disastrous paradoxes in set theory, which is
   - *Berry's Paradox* $\quad$ an expression which is self-referenced negatively
   - *Russell's Paradox* $\quad$ exemplified by \[\{x|x\notin x\}\]

** Sets - An Informal View
   None of the later work will depend on this informal description.

   Skip if you want.

   First we gather around all the things that are not sets
   but we want to have as members of our sets, call such things as atoms.
   Atoms are not sets of any kind. We put all of those atoms in a set
   which could be noted as $A$, it is the first set in out description.

   And now imagine a hierarchy
   \[
   V_0 \subseteq V_1 \subseteq V_2 \subseteq \cdot\cdot\cdot
   \]
   of sets, and we take $V_0 = A$, the set of all atoms, and we difine
   the rest of the sets recursively, for example:
   \[
   V_1 = V_0 \cup \mathscr{P}V_0 = A \cup \mathscr{P}A
   \]
   so, the general formula for constructing this hierarchy of sets would be:
   \[
   V_{n+1} = V_n \cup \mathscr{P}V_n
   \]
   Thus we obtain $V_0, V_1, V_2,....$, but this infinite hierarchy
   does not include enough sets. For example, the infinite set
   \[
   \{\emptyset,\{\emptyset\},\{\{\emptyset\}\},...\}
   \]
   but we have $\emptyset \in V_1$,$\{ \emptyset \} \in V_2 $, etc.
   To remedy this lack, we contrust an infinite union
   \[
   V_{\omega} = V_0\cup V_1 \cup \cdot\cdot\cdot
   \]
   and then let $V_{\omega+1} = V_{\omega} \cup \mathscr{P}V_{\omega}$,
   and in general for any $\alpha$,
   \[
   V_{\alpha+1} = V_{\alpha} \cup \mathscr{P} V_{\alpha}
   \]
   so we could conclude that for each set $S$, $\exists \alpha$ s.t. $S \in V_{\alpha}$

   And for now, if we banish the atoms, instead take $A=\emptyset$, and here is the ordinals.


** Classes
   There is no "set of all sets", which is later presented as a theorem, provable from the axioms.
